const types = {
    GET_NEW_RELEASE_REQUEST : "GET_NEW_RELEASE_REQUEST",
    GET_NEW_RELEASE_SUCCESS : "GET_NEW_RELEASE_SUCCESS", 
    GET_FEATURED_LIST_REQUEST : "GET_FEATURED_LIST_REQUEST", 
    GET_FEATURED_LIST_SUCCESS : "GET_FEATURED_LIST_SUCCESS", 
    GET_BROWSE_GENRES_REQUEST : "GET_BROWSE_GENRES_REQUEST",
    GET_BROWSE_GENRES_SUCCESS : "GET_BROWSE_GENRES_SUCCESS"
}

export default types;